on: 
  push:
    branches:
      - main

jobs:
  macos-build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Command Line Tools
        run: xcode-select --install || true

      - name: Install base tools and dependencies
        run: |
          brew update
          brew install automake libtool pkg-config boost gcc

      - name: Set Compiler and Architecture Variables
        run: |
          export CC=/usr/bin/clang
          export CXX=/usr/bin/clang++
          export ARCHFLAGS="-arch x86_64"

      - name: List dependencies in /depends/packages
        run: ls depends/packages

      - name: Auto-generate configuration
        run: ./autogen.sh

      - name: Configure with depends folder
        env:
          CC: /usr/bin/clang
          CXX: /usr/bin/clang++
          ARCHFLAGS: "-arch x86_64"
        run: |
          export CXXFLAGS="-I$PWD/depends/x86_64-apple-darwin/include $ARCHFLAGS"
          export LDFLAGS="-L$PWD/depends/x86_64-apple-darwin/lib -ldb_cxx $ARCHFLAGS"
          CONFIG_SITE=$PWD/depends/x86_64-apple-darwin/share/config.site \
          ./configure --prefix=$(pwd)/depends/x86_64-apple-darwin \
          --build=x86_64-apple-darwin --host=x86_64-apple-darwin --target=x86_64-apple-darwin \
          --disable-bench --disable-tests --disable-dependency-tracking --disable-werror --enable-gui \
          || (cat config.log && false)

      - name: Compile with custom dependencies
        run: |
          cd src
          make -j2 VERBOSE=1

      - name: Strip binaries
        run: |
          cd ./src
          strip tokenpay

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: ./src/tokenpay







