on: 
  push:
    branches:
      - main  # or your target branch

jobs:
  windows32-ubuntu20:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Install base tools and Qt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libtool automake pkg-config bsdmainutils curl git \
              g++-mingw-w64-i686 mingw-w64-i686-dev libx11-dev libxext-dev libxtst-dev libxcb1-dev \
              libx11-xcb-dev libxcb-glx0-dev libxrender-dev libxcb-render-util0-dev libxcb-shape0-dev \
              libxcb-xfixes0-dev
          sudo update-alternatives --set i686-w64-mingw32-g++ /usr/bin/i686-w64-mingw32-g++-posix

      - name: Verify dependencies in /depends/packages
        run: |
          ls depends/packages  # Lists available packages for verification
          # Additional commands can be added here if needed to handle packages

      - name: Build dependencies in the depends folder
        run: |
          PATH=$(echo "$PATH" | sed -e 's/:\/mnt.*//g')
          cd depends/
          make HOST=i686-w64-mingw32 -j1 VERBOSE=1

      - name: Auto-generate configuration
        run: ./autogen.sh

      - name: Configure with depends folder
        run: |
          CONFIG_SITE=$PWD/depends/i686-w64-mingw32/share/config.site ./configure --prefix=$(pwd)/depends/i686-w64-mingw32 --disable-bench --disable-tests --disable-dependency-tracking --disable-werror --bindir=$(pwd)/release/bin --libdir=$(pwd)/release/lib

      - name: Compile with custom dependencies
        run: |
          cd src  # Ensure correct directory if Makefile is in /src
          make -j1 VERBOSE=1

      - name: Strip binaries
        run: |
          cd ./src
          strip tokenpay.exe
          strip tokenpayd.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows32-ubuntu20-build
          path: ./src/tokenpay.exe  # Adjust path to the location of the executable

  windows64-ubuntu20:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Install base tools and Qt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libtool automake pkg-config bsdmainutils curl git \
              g++-mingw-w64-x86-64 libx11-dev libxext-dev libxtst-dev libxcb1-dev libx11-xcb-dev \
              libxcb-glx0-dev libxrender-dev libxcb-render-util0-dev libxcb-shape0-dev libxcb-xfixes0-dev
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix 

      - name: Verify dependencies in /depends/packages
        run: |
          ls depends/packages  # Lists available packages for verification
          # Additional commands can be added here if needed to handle packages

      - name: Build dependencies in the depends folder
        run: |
          PATH=$(echo "$PATH" | sed -e 's/:\/mnt.*//g')
          cd depends/
          make HOST=x86_64-w64-mingw32 -j1 VERBOSE=1

      - name: Auto-generate configuration
        run: ./autogen.sh

      - name: Configure with depends folder
        run: |
          CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --enable-scrypt-sse2 --prefix=$(pwd)/depends/x86_64-w64-mingw32 --disable-bench --disable-tests

      - name: Compile with custom dependencies
        run: |
          cd src  # Ensure correct directory if Makefile is in /src
          make -j1 VERBOSE=1

      - name: Strip binaries
        run: |
          cd ./src
          strip tokenpay.exe
          strip tokenpayd.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows64-ubuntu20-build
          path: ./src/tokenpay.exe  # Adjust path to the location of the executable

