on:
  push

jobs:
  macos12:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v4

      - name: git config credential.helper
        run: git config credential.helper

      - name: Check GCC
        run: llvm-gcc --version
        
      - name: brew install java openjdk
        run: brew install openjdk@21

      - name: Clone custom our MacPorts repository
        run: |
          git clone https://github.com/t3sting3/macports-ports.git
          echo "Custom MacPorts repository cloned."

      - name: Install MacPorts 2.8.1
        run: |
          curl -O https://distfiles.macports.org/MacPorts/MacPorts-2.8.1.tar.gz
          tar xvf MacPorts-2.8.1.tar.gz
          cd MacPorts-2.8.1
          ./configure --with-applications-dir=/Applications --prefix=/opt/local
          make
          sudo make install
          echo "MacPorts installed."

      - name: Configure PATH to include our MacPorts (in-line)
        run: |
          export PATH=/opt/local/bin:/opt/local/sbin:$PATH
          echo "PATH updated to include MacPorts."
          port version

      - name: Configure MacPorts to use our custom ports repository
        run: |
          export PATH=/opt/local/bin:/opt/local/sbin:$PATH
          sudo sh -c 'echo "file://$(pwd)/macports-ports [nosync]" > /opt/local/etc/macports/sources.conf'
          cd macports-ports
          sudo portindex
          echo "MacPorts configured with the custom ports."
          
      - name: Install Java Developer Package
        run: |
          # Fetch list of software available for update
          softwareupdate --list
          softwareupdate --install 'Command Line Tools for Xcode-13.1'

      - name: Verify Java Installation
        run: |
          /usr/libexec/java_home
          java -version

      - name: Set Xcode 13.1
        run: sudo xcode-select -switch /Applications/Xcode_13.1.app

      - name: Install Boost 1.65.1 with custom patches
        run: |
          export PATH=/opt/local/bin:/opt/local/sbin:$PATH
          cd macports-ports/databases/db48 && ls
          sudo port -v install db48 cd .. && cd ..
          cd macports-ports/lang/python27 && ls
          sudo port install python27
          sudo port -f activate python27
          cd macports-ports/devel/boost && ls
          sudo port install boost @1.65.1 +without-icu
          echo "Boost 1.65.1 installed from the custom repository with patches."

      - name: Verify Boost installation
        run: |
          export PATH=/opt/local/bin:/opt/local/sbin:$PATH
          port installed boost

      - name: Brew link dependencies
        run: brew link qt@5 berkeley-db@4

      - name: Which clang/Xcode
        run: clang --version

      - name: Auto generate
        run: ./autogen.sh

      - name: Configure
        run: ./configure --disable-dependency-tracking --disable-werror --bindir=`pwd`/release/bin --libdir=`pwd`/release/lib

      - name: Make
        run: make -j4

      - name: Make .dmg
        run: make deploy

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tpay-macos13
          path: |
            *.dmg
