on:
  push

jobs:
  macos12:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v4

      - name: git config credential.helper
        run: git config credential.helper

      - name: Check GCC
        run: llvm-gcc --version
        
      - name: Install Java via Homebrew
        run: brew install openjdk@21

      - name: Clone custom MacPorts repository
        run: |
          git clone https://github.com/t3sting3/macports-ports.git
          echo "Custom MacPorts repository cloned."

      - name: Install MacPorts 2.8.1
        run: |
          curl -O https://distfiles.macports.org/MacPorts/MacPorts-2.8.1.tar.gz
          tar xvf MacPorts-2.8.1.tar.gz
          cd MacPorts-2.8.1
          ./configure --with-applications-dir=/Applications --prefix=/opt/local
          make
          sudo make install
          echo "MacPorts installed."

      - name: Configure PATH to include MacPorts
        run: |
          export PATH=/opt/local/bin:/opt/local/sbin:$PATH
          echo "PATH updated to include MacPorts."
          port version

      - name: Install Java Developer Package (legacy)
        run: |
          curl -O https://support.apple.com/downloads/DL1572/en_US/javaforosx.dmg
          hdiutil attach javaforosx.dmg
          sudo installer -pkg /Volumes/Java\ for\ OS\ X\ 2017-001/JavaForOSX.pkg -target /
          hdiutil detach /Volumes/Java\ for\ OS\ X\ 2017-001
          echo "Legacy Java Developer Package installed."

      - name: Verify Java Installation
        run: |
          /usr/libexec/java_home
          java -version

      - name: Set Xcode 13.1
        run: sudo xcode-select -switch /Applications/Xcode_13.1.app

      - name: Install DB5.3 with Java Headers
        run: |
          export PATH=/opt/local/bin:/opt/local/sbin:$PATH
          cd macports-ports/databases/db48
          sudo port -v install db48 +java
          echo "DB5.3 installed with Java headers."

      - name: Install Boost 1.65.1 with custom patches
        run: |
          export PATH=/opt/local/bin:/opt/local/sbin:$PATH
          cd macports-ports/devel/boost
          sudo port -v install boost @1.65.1 +without-icu
          echo "Boost 1.65.1 installed from the custom repository with patches."

      - name: Verify Boost installation
        run: |
          export PATH=/opt/local/bin:/opt/local/sbin:$PATH
          port installed boost

      - name: Brew link dependencies
        run: brew link qt@5 berkeley-db@4

      - name: Which clang/Xcode
        run: clang --version

      - name: Auto generate
        run: ./autogen.sh

      - name: Configure
        run: ./configure --disable-dependency-tracking --disable-werror --bindir=`pwd`/release/bin --libdir=`pwd`/release/lib

      - name: Make
        run: make -j4

      - name: Make .dmg
        run: make deploy

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tpay-macos13
          path: |
            *.dmg
