on: 
  push:
    branches:
      - main

jobs:
  macos-build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install base tools and dependencies
        run: |
          brew update
          brew install automake libtool pkg-config boost

      - name: Verify dependencies in /depends/packages
        run: ls depends/packages

      - name: Build specific dependencies in the depends folder
        run: |
          cd depends/
          make -j2 HOST=x86_64-apple-darwin VERBOSE=1

      - name: Auto-generate configuration
        run: ./autogen.sh

      - name: Configure with depends folder
        run: |
          export CXXFLAGS="-I$PWD/depends/x86_64-apple-darwin/include"
          export LDFLAGS="-L$PWD/depends/x86_64-apple-darwin/lib -ldb_cxx"
          CONFIG_SITE=$PWD/depends/x86_64-apple-darwin/share/config.site ./configure --prefix=$(pwd)/depends/x86_64-apple-darwin --disable-bench --disable-tests --disable-dependency-tracking --disable-werror --enable-gui

      - name: Compile with custom dependencies
        run: |
          cd src
          make -j2 VERBOSE=1

      - name: Strip binaries
        run: |
          cd ./src
          strip tokenpay

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: ./src/tokenpay



