on:
  push

jobs:
  macos12:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v4

      - name: git config credential.helper
        run: git config credential.helper

      - name: Check GCC
        run: llvm-gcc --version

      - name: Install Java Developer Package with Brew
        run: |
          brew install --cask zulu
          echo "Java Developer Package installed."

      - name: Verify Java Developer Package Installation
        run: |
          /usr/libexec/java_home -v 1.6
          java -version

      - name: Install MacPorts 2.8.1
        run: |
          curl -O https://distfiles.macports.org/MacPorts/MacPorts-2.8.1.tar.gz
          tar xvf MacPorts-2.8.1.tar.gz
          cd MacPorts-2.8.1
          ./configure --with-applications-dir=/Applications --prefix=/opt/local
          make
          sudo make install
          echo "MacPorts installed."

      - name: Ensure PATH is updated for MacPorts
        shell: bash
        run: |
          echo 'export PATH=/opt/local/bin:/opt/local/sbin:$PATH' >> ~/.bash_profile
          source ~/.bash_profile
          sudo /opt/local/bin/port version
          echo "PATH updated to include MacPorts."

      - name: Clone MacPorts Ports Repository
        run: |
          git clone https://github.com/macports/macports-ports.git
          echo "MacPorts Ports repository cloned."

      - name: Configure MacPorts to use the cloned repository
        run: |
          sudo sh -c 'echo "file://$(pwd)/macports-ports [nosync]" > /opt/local/etc/macports/sources.conf'
          echo "sources.conf updated to use custom repository."

      - name: Rebuild Port Index
        run: |
          export PATH=/opt/local/bin:/opt/local/sbin:$PATH
          sudo /opt/local/bin/portindex
          echo "Port index rebuilt."

      - name: Install Xcode Command Line Tools
        run: |
          sudo xcode-select --switch /Applications/Xcode_13.1.app

      - name: Verify Xcode Installation
        run: xcodebuild -version

      - name: Install DB5.3 with Java Headers
        run: |
          export PATH=/opt/local/bin:/opt/local/sbin:$PATH
          sudo /opt/local/bin/port -v install db53 +java
          echo "DB5.3 installed with Java headers."

      - name: Install Boost 1.65.1 with custom patches
        run: |
          export PATH=/opt/local/bin:/opt/local/sbin:$PATH
          sudo /opt/local/bin/port -v install boost @1.65.1 +without-icu
          echo "Boost 1.65.1 installed."

      - name: Verify Boost installation
        run: |
          export PATH=/opt/local/bin:/opt/local/sbin:$PATH
          sudo /opt/local/bin/port installed boost

      - name: Brew link dependencies
        run: brew link qt@5 berkeley-db@4

      - name: Which clang/Xcode
        run: clang --version

      - name: Auto generate
        run: ./autogen.sh

      - name: Configure
        run: ./configure --disable-dependency-tracking --disable-werror --bindir=`pwd`/release/bin --libdir=`pwd`/release/lib

      - name: Make
        run: make -j4

      - name: Make .dmg
        run: make deploy

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tpay-macos13
          path: |
            *.dmg
