on:
  push

jobs:
  macos12:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v4

      - name: git config credential.helper
        run: git config credential.helper

      - name: Check GCC
        run: llvm-gcc --version

      - name: Install MacPorts 2.8.1
        run: |
          curl -O https://distfiles.macports.org/MacPorts/MacPorts-2.8.1.tar.gz
          tar xvf MacPorts-2.8.1.tar.gz
          cd MacPorts-2.8.1
          ./configure --with-applications-dir=/Applications --prefix=/opt/local
          make
          sudo make install
          echo "MacPorts installed."

      - name: Ensure PATH is updated for MacPorts
        shell: bash
        run: |
          echo 'export PATH=/opt/local/bin:/opt/local/sbin:$PATH' >> ~/.bash_profile
          source ~/.bash_profile
          sudo /opt/local/bin/port version
          echo "PATH updated to include MacPorts."

      - name: Clone MacPorts Ports Repository
        run: |
          git clone https://github.com/macports/macports-ports.git
          echo "MacPorts Ports repository cloned."

      - name: Configure MacPorts to use the cloned repository
        run: |
          sudo sh -c 'echo "file://$(pwd)/macports-ports [nosync]" > /opt/local/etc/macports/sources.conf'
          echo "sources.conf updated to use the cloned repository."

      - name: Rebuild Port Index
        run: |
          cd macports-ports
          sudo /opt/local/bin/portindex
          echo "Port index rebuilt from the custom repository."

      - name: Check if Xcode Command Line Tools are installed
        run: |
          if ! xcode-select -p; then
            echo "Xcode Command Line Tools are not installed. Installing now..."
            sudo xcode-select --install
          else
            echo "Xcode Command Line Tools are already installed."
          fi

      - name: Install Legacy Java Developer Package
        run: |
          curl -O https://support.apple.com/downloads/DL1572/en_US/javaforosx.dmg
          hdiutil attach javaforosx.dmg
          sudo installer -pkg /Volumes/Java\ for\ OS\ X\ 2017-001/JavaForOSX.pkg -target /
          hdiutil detach /Volumes/Java\ for\ OS\ X\ 2017-001
          echo "Legacy Java Developer Package installed."

      - name: Install DB5.3 with Java Headers
        run: |
          export PATH=/opt/local/bin:/opt/local/sbin:$PATH
          sudo /opt/local/bin/port -v install db53 +java
          echo "DB5.3 installed with Java headers."

      - name: Install Boost 1.65.1 with custom patches
        run: |
          export PATH=/opt/local/bin:/opt/local/sbin:$PATH
          sudo /opt/local/bin/port -v install boost @1.65.1 +without-icu
          echo "Boost 1.65.1 installed."

      - name: Verify Boost installation
        run: |
          export PATH=/opt/local/bin:/opt/local/sbin:$PATH
          sudo /opt/local/bin/port installed boost

      - name: Brew link dependencies
        run: brew link qt@5 berkeley-db@4

      - name: Which clang/Xcode
        run: clang --version

      - name: Auto generate
        run: ./autogen.sh

      - name: Configure
        run: ./configure --disable-dependency-tracking --disable-werror --bindir=`pwd`/release/bin --libdir=`pwd`/release/lib

      - name: Make
        run: make -j4

      - name: Make .dmg
        run: make deploy

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tpay-macos13
          path: |
            *.dmg
