on:
  push

jobs:
  macos12:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v4

      - name: git config credential.helper
        run: git config credential.helper

      - name: Get previous Xcode and switch to it
        run: ls -la /Applications/Xcode* && sudo xcode-select -switch /Applications/Xcode_13.1.app

      - name: Check GCC
        run: llvm-gcc --version

      - name: Install MacPorts
        run: |
          curl -O https://distfiles.macports.org/MacPorts/MacPorts-2.8.1.tar.bz2
          tar xf MacPorts-2.8.1.tar.bz2
          cd MacPorts-2.8.1
          ./configure --prefix=/opt/local
          make
          sudo make install

      - name: Add MacPorts to PATH
        run: echo "/opt/local/bin:/opt/local/sbin" >> $GITHUB_PATH

      - name: Create Local Ports Repository
        run: |
          sudo mkdir -p /opt/local/var/macports/sources/local/devel/boost/files
          sudo chmod -R 777 /opt/local/var/macports/sources/local

      - name: Download and Extract Boost 1.65.1 Portfile and Patches
        run: |
          cd /opt/local/var/macports/sources/local/devel/boost
          curl -O https://trac.macports.org/raw-attachment/ticket/50671/boost_1.65.1.tar.bz2
          tar xf boost_1.65.1.tar.bz2

      - name: List Extracted Files for Debugging
        run: |
          ls -la /opt/local/var/macports/sources/local/devel/boost/boost

      - name: Move Portfile and Files Directory
        run: |
          sudo mv /opt/local/var/macports/sources/local/devel/boost/boost/Portfile /opt/local/var/macports/sources/local/devel/boost/Portfile
          sudo mv /opt/local/var/macports/sources/local/devel/boost/boost/files /opt/local/var/macports/sources/local/devel/boost/files

      - name: Create Missing PortGroup Directory
        run: |
          sudo mkdir -p /opt/local/var/macports/portgroups

      - name: Download Required PortGroup File
        run: |
          curl -O https://raw.githubusercontent.com/macports/macports-ports/master/PortGroup/compiler_blacklist_versions-1.0.tcl
          sudo mv compiler_blacklist_versions-1.0.tcl /opt/local/var/macports/portgroups/

      - name: Update MacPorts to Include Local Repo
        run: |
          echo "file:///opt/local/var/macports/sources/local [nosync]" | sudo tee -a /opt/local/etc/macports/sources.conf
          sudo portindex /opt/local/var/macports/sources/local

      - name: Install Boost 1.65.1 with Local Portfile
        run: sudo port install boost @1.65.1

      - name: Verify Boost Installation
        run: port installed boost

      - name: Brew link dependencies
        run: brew link qt@5 berkeley-db@4

      - name: Which clang/Xcode
        run: clang --version

      - name: Auto generate
        run: ./autogen.sh

      - name: Configure
        run: ./configure --disable-dependency-tracking --disable-werror --bindir=`pwd`/release/bin --libdir=`pwd`/release/lib

      - name: Make
        run: make -j4

      - name: Make .dmg
        run: make deploy

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tpay-macos13
          path: |
            *.dmg
