on:
  push

jobs:
  macos12:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v4

      - name: Install base tools and dependencies
        run: |
          brew install automake libtool pkg-config boost

      - name: Verify dependencies in /depends/packages
        run: ls depends/packages

      - name: Build dependencies in the depends folder
        run: |
          PATH=$(echo "$PATH" | sed -e 's/:\/mnt.*//g')
          cd depends/
          make HOST=x86_64-apple-darwin -j1 VERBOSE=1

      - name: Auto-generate configuration
        run: ./autogen.sh

      - name: Configure with depends folder
        run: |
          export CXXFLAGS="-I$PWD/depends/x86_64-apple-darwin/include"
          export LDFLAGS="-L$PWD/depends/x86_64-apple-darwin/lib -ldb_cxx"
          CONFIG_SITE=$PWD/depends/x86_64-apple-darwin/share/config.site ./configure --prefix=$(pwd)/depends/x86_64-apple-darwin --disable-bench --disable-tests --disable-dependency-tracking --disable-werror --enable-gui

      - name: Compile with custom dependencies
        run: |
          cd src
          make -j4 VERBOSE=1

      - name: Strip binaries
        run: |
          cd ./src
          strip tokenpay

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos12-build
          path: ./src/tokenpay

