on:
  push

jobs:
  macos12:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v4

      - name: git config credential.helper
        run: git config credential.helper

      # Install Zulu OpenJDK 11 from Homebrew
      - name: /usr/libexec/java_home -V
        run: /usr/libexec/java_home -V
        
      - name: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/include
        run: ls /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/include
        
      - name: echo $JAVA_HOME
        run: echo $JAVA_HOME
        
      - name: 
        run: xcode-select --install && sudo xcodebuild -runFirstLaunch