on:
  push
jobs:
  macos12:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v4

      - name: git config credential.helper
        run: git config credential.helper
        
      - name: get previous xcode and switch to it
        run: ls -la /Applications/Xcode* && sudo xcode-select -switch /Applications/Xcode_13.1.app
        
      - name: check gcc
        run: llvm-gcc --version

      - name: Brew install base dependencies
        run: brew install --quiet automake berkeley-db@4 miniupnpc qt@5 gperf qrencode librsvg && curl -L https://raw.githubusercontent.com/vergecurrency/protobuf261/master/protobuf261.rb > protobuf261.rb && brew install protobuf261.rb && brew unlink openssl@3 && brew link --overwrite openssl@1.1
      
      - name: download and untar boost and download patch
        run: wget http://sourceforge.net/projects/boost/files/boost/1.65.0/boost_1_65_0.tar.gz && tar -xzvf boost_1_65_0.tar.gz
        
      - name: project-config jam
        run: |
            cd boost_1_65_0 && echo 'using clang : : clang++-13 : <cxxflags>"-std=c++11 -stdlib=libc++ -Wno-deprecated-declarations" ;' >> project-config.jam
        
      - name: bootstrap boost
        run: cd boost_1_65_0 && ./bootstrap.sh --with-toolset=clang || true

      - name: list files
        run: ls -al
        
      - name: list inside boost
        run: cd boost_1_65_0 && ls -al
      
      - name: b2
        run: cd boost_1_65_0 && sudo ./b2 --with-system --with-filesystem --with-chrono --with-date_time --with-iostreams --with-program_options --with-thread --with-test cxxflags="-std=c++11 -Wno-deprecated-declarations" toolset=darwin install
        
      - name: Brew link dependencies
        run: brew link qt@5 berkeley-db@4
        
      - name: which clang/xcode
        run: clang --version

      - name: Auto generate
        run: ./autogen.sh

      - name: configure
        run: ./configure --disable-dependency-tracking --disable-werror --bindir=`pwd`/release/bin --libdir=`pwd`/release/lib

      - name: make
        run: make -j4

      - name: make .dmg
        run: make deploy
        
      - name: Upload Bootstrap Log if Build Fails
        if: failure()  # Only run this step if the previous step failed
        uses: actions/upload-artifact@v3
        with:
          name: bootstrap.log
          path: /home/runner/work/tokenpay-linux/tokenpay-linux/boost_1_65_0/bootstrap.log

      - uses: actions/upload-artifact@v4
        with:
          name: tpay-macos13
          path: |
            *.dmg