on:
  push
jobs:
  macos12:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v4

      - name: git config credential.helper
        run: git config credential.helper
        
      - name: get previous xcode and switch to it
        run: ls -la /Applications/Xcode* && sudo xcode-select -switch /Applications/Xcode_13.1.app
        
      - name: check gcc
        run: llvm-gcc --version

      - name: Brew install base dependencies
        run: brew install --quiet automake berkeley-db@4 miniupnpc qt@5 gperf qrencode librsvg && curl -L https://raw.githubusercontent.com/vergecurrency/protobuf261/master/protobuf261.rb > protobuf261.rb && brew install protobuf261.rb && brew unlink openssl@3 && brew link --overwrite openssl@1.1
      
      - name: git clone boost
        run: git clone --depth 1 --branch boost-1.65.1 https://github.com/boostorg/boost
        
      - name: checkout boost version
        run: cd boost && git checkout -f boost-1.65.1
        
      - name: go into and run Bootstrap
        run: cd boost && ./bootstrap.sh
        
      - name: run b2
        run: cd boost && ./b2 --with-system --with-filesystem --with-chrono --with-date_time --with-iostreams --with-program_options --with-thread --with-test install
        
      - name: Brew link dependencies
        run: brew link qt@5 berkeley-db@4
        
      - name: which clang/xcode
        run: clang --version

      - name: Auto generate
        run: ./autogen.sh

      - name: configure
        run: ./configure --disable-dependency-tracking --disable-werror --bindir=`pwd`/release/bin --libdir=`pwd`/release/lib

      - name: make
        run: make -j4

      - name: make .dmg
        run: make deploy
        
      - name: Upload Bootstrap Log if Build Fails
        if: failure()  # Only run this step if the previous step failed
        uses: actions/upload-artifact@v4
        with:
          name: bootstrap.log
          path: ./boost/bootstrap.log

      - uses: actions/upload-artifact@v4
        with:
          name: tpay-macos13
          path: |
            *.dmg