name: Ubuntu Dependencies

on:
  push:

jobs:
  ubuntu20-depends:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update apt repositories
        run: sudo apt-get update

      - name: Install base dependencies
        run: sudo apt-get install -y build-essential xutils-dev libtool gperf autotools-dev automake pkg-config bsdmainutils libattr1-dev make automake bison byacc cmake curl g++-multilib binutils-gold python3
        continue-on-error: true

      - name: Build depends
        run: cd depends && make -j4 HOST=x86_64-linux-gnu

      - name: Auto-generate configuration files
        run: ./autogen.sh

      - name: Configure project
        run: CONFIG_SITE=$PWD/depends/x86_64-linux-gnu/share/config.site ./configure --enable-gui --disable-bench --disable-tests --disable-dependency-tracking --disable-werror --prefix=$PWD/depends/x86_64-linux-gnu

      - name: Build project
        run: make -j4
