on:
  push

jobs:
  ubuntu20:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Update apt repos
        run: sudo apt-get update

      - name: Install base dependencies
        run: sudo apt-get install build-essential xutils-dev libicu-dev libtool gperf autotools-dev automake pkg-config bsdmainutils libattr1-dev make automake bison byacc cmake curl g++-multilib binutils-gold bison byacc python2

      - name: Set Python 2 as default
        run: |
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 2
          sudo update-alternatives --set python /usr/bin/python2

      - name: Verify Python Version
        run: python --version  # Should print Python 2.7.x

      - name: install openssl 1.1.0e
        run: wget https://github.com/openssl/openssl/releases/download/OpenSSL_1_1_0e/openssl-1.1.0e.tar.gz
        
      - name: untar openssl, go in and run config
        run: tar -xzf openssl-1.1.0e.tar.gz
        
      - name: Patch the Perl file to fix "glob" error
        run: |
          cd openssl-1.1.0e
          # Assuming the error is in util/perl/OpenSSL/config.pm, update the path if needed
          sed -i '1i use File::Glob qw(glob);' util/perl/OpenSSL/config.pm
          # Optionally verify the patch
          head -n 10 util/perl/OpenSSL/config.pm
      
      - name: go in and configure then run  
        run: cd openssl-1.1.0e && ./Configure --prefix=/usr/local/ssl 
        
      - name: go in and make and install openssl  
        run: make && sudo make install
      
      - name: Build depends
        run: cd depends/ && make -j4 HOST=x86_64-linux-gnu

      - name: Add uic path to environment
        run: echo "/home/runner/work/tokenpay-linux/tokenpay-linux/depends/x86_64-linux-gnu/native/bin" >> $GITHUB_PATH

      - name: Verify uic path
        run: which uic

      - name: Auto generate
        run: ./autogen.sh

      - name: configure
        run: CONFIG_SITE=$PWD/depends/x86_64-linux-gnu/share/config.site ./configure --enable-gui --disable-bench --disable-tests --disable-dependency-tracking --disable-werror --prefix=`pwd`/depends/x86_64-linux-gnu --bindir=`pwd`/release/bin --libdir=`pwd`/release/lib

      - name: make
        run: make -j4
