on:
  push
jobs:
  ubuntu20:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Update apt repos
        run: sudo apt-get update

      - name: install boost
        run: wget https://sourceforge.net/projects/boost/files/boost/1.62.0/boost_1_62_0.tar.gz
      - name: untar boost
        run: tar xzvf boost_1_62_0.tar.gz
        
      - name: go in and run bootstrap
        run: cd boost_1_62_0 && ./bootstrap.sh --prefix=/usr/local --with-libraries=chrono,date_time,iostreams,filesystem,program_options,system,thread,test

      - name: run b2 
        run: cd boost_1_62_0 && sudo ./b2 install
        
      - name: install berkeley db 4.8
        run: wget http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz && tar -xzvf db-4.8.30.NC.tar.gz 
        
      - name: build bdb4.8
        run: cd db-4.8.30.NC/build_unix/ && ../dist/configure --enable-cxx && make && make install
        
      - name: Install base dependencies
        run: sudo apt-get install build-essential libtool autotools-dev automake pkg-config zlib1g-dev libevent-dev bsdmainutils git libseccomp-dev libcap-dev libminiupnpc-dev libqt5gui5 libqt5core5a libqt5webkit5-dev libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler libqrencode-dev

      - name: Auto generate
        run: ./autogen.sh

      - name: configure
        run: ./configure --enable-gui --disable-werror --prefix=`pwd`/depends/x86_64-linux-gnu --bindir=`pwd`/release/bin --libdir=`pwd`/release/lib

      - name: make
        run: make -j4
        
      - name: strip
        run: cd /home/runner/work/tokenpay-linux/tokenpay-linux/src && strip tokenpayd && strip tokenpay

      - uses: actions/upload-artifact@v4
        with:
          name: tpay-ubuntu20
          path: |
            ./src/tokenpayd
            ./src/tokenpay